# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Welcome to My First Azure Pipeline
  displayName: 'My First Azure Pipeline'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'mohdwazid-dockerhub'
    repository: 'mohdwazid/k8s-docker-repo'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: latest

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'svc-k8s-cluster'
    namespace: 'default'
    manifests: 'deployment.yaml'