---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-nginx
  template:
    metadata:
      labels:
        app: k8s-nginx
    spec:
      containers:
      - name: k8s-nginx
        image: paulbouwer/hello-kubernetes:1.5
        imagePullPolicy: Always
        ports:
          - containerPort: 8080