apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in-k8s-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: <SSLIP.IO-NAME>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lb-k8-nginx
            port:
              number: 80