---
apiVersion: v1
kind: Service              # 1
metadata:
  name: k8-nginx
spec: 
  type: LoadBalancer
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 8080         # 5
  selector:                # 6
    app: k8-nginx       # 7